version: "3.9"

services:
  db:
    image: postgres:16
    container_name: ccopt_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ccopt
      POSTGRES_PASSWORD: ccoptpassword
      POSTGRES_DB: ccopt_db
    ports:
      - "5432:5432"
    volumes:
      - ccopt_pg_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: ccopt_redis
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  ccopt_pg_data:
